# Generated by Django 4.0.6 on 2022-07-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_price_product_stripe_product_id_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
