# Generated by Django 4.0.6 on 2022-07-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stripe_product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
