# Generated by Django 4.0.6 on 2022-07-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_price_price_cents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='cents',
            new_name='price',
        ),
    ]
